### ISSUE TITLE
Dark face that cannot be visible 

### ISSUE THREAD

**Issue by mekya** [ant-media/conference-call-application#200]
Check the images. The user face is dark. 
![WhatsApp Image 2024-01-15 at 14 15 15](https://github.com/ant-media/conference-call-application/assets/3456251/02a19d1d-b00b-4139-b4ac-8deedd20fbef)
![WhatsApp Image 2024-01-15 at 14 16 47](https://github.com/ant-media/conference-call-application/assets/3456251/37d33156-7686-47c8-b2d1-7da757211ba6)

**Comment by mustafaboleken** [comment]
This issue is related to lightning. You can also check this scenario on the other conference solutions like Google Meet.

![Screenshot 2024-01-18 at 15 21 46](https://github.com/ant-media/conference-call-application/assets/23143596/58d4209d-b23f-4201-8466-134f95c775fc)

![Screenshot 2024-01-18 at 15 21 39](https://github.com/ant-media/conference-call-application/assets/23143596/5c838565-469f-4df7-b262-ed124ca7e0b6)
