### ISSUE TITLE
Can't deploy ConferenceCall-v2.9.0.war on Ant Media Server Enterprise

### ISSUE THREAD

**Issue by HollowCrusader** [ant-media/conference-call-application#266]
I've been trying to deploy the war file to the Ant Media Server and it just keeps showing the activity indicator for about 30 minutes.

![Screenshot 2024-05-16 at 1 25 08 PM](https://github.com/ant-media/conference-call-application/assets/28148217/96a8dd4b-56be-4191-8661-d795b72b6c52)

I've checked the console log, some errors occurred during the deployment process.

![Screenshot 2024-05-16 at 1 25 35 PM](https://github.com/ant-media/conference-call-application/assets/28148217/073ced5f-3b7e-451a-8dd4-c547ce4f900e)

The AMS's Enterprise Edition version is 2.6.2

**Comment by mustafaboleken** [comment]
Hi @HollowCrusader 

Your conference application war file's version and your Ant Media Server version must match. You can find the version 2.6.2 from https://github.com/ant-media/conference-call-application/releases
But I highly recommend you to upgrade your server because, conference application is significantly improved after version 2.8.2

**Comment by HollowCrusader** [comment]
I was able to deploy it and get it working using the match version. Also, that is a great idea, I will go ahead and install the latest version of the ant media server, or is there a way I can receive an update?

**Comment by mustafaboleken** [comment]
Hi @HollowCrusader,

If you are using marketplace version, you need to create a new instance from scratch. If you install it manually, you can just get the latest version from antmedia.io website.
