### ISSUE TITLE
Add join as a play only option

### ISSUE THREAD

**Issue by mustafaboleken** [ant-media/conference-call-application#28]

**Comment by asharamseervi** [comment]
Hi @mustafaboleken & @burak-58, this issue was referenced to a PR that doesn't describe what that PR does. I got surprised when this referenced issue also didn't contain any such information. Just the title alone.

It would be great if you guys start briefing brief details (specially in issues if not pr) but it would be nice to have even a one-liner at PR (and issue description). We should start practicing it.
