### ISSUE TITLE
Circle Recording Issue while screen sharing

### ISSUE THREAD

**Issue by burak-58** [ant-media/conference-call-application#322]

**Comment by Mohit-3196** [comment]
I faced an issue with stopping the recording issue a couple of weeks back when using circle and media push plugin.
The issue reproduction scenario was like this:
1.  Create a docker image with the media push plugin.
2. Use the image in K8.
3. Join a room and share the screen.
4. Start the recording 
5. Stop the recording

Issue: The recording did not stop because of an error related to the adaptor.

I checked with the latest AMS snapshot with the latest snapshot of Circle and on Friday and did not face the issue.
